version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  postgres:
    image: postgres:latest
    container_name: postgres-server
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
      POSTGRES_USER: user
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1434:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - my-network

  trino:
    image: trinodb/trino:latest
    container_name: trino
    depends_on:
      - mysql
      - postgres
      - mssql
    ports:
      - "8081:8081"
    volumes:
      - ./etc:/etc/trino
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql-data:
  postgres-data:
  mssql-data:
